apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    qingyuanos.com/catalog-by: '{"version": "v1alpha", "lib": "https://github.com/qingyuancloud/harpoon", "module": "https://github.com/sonatype/docker-nexus3"}'
  labels:
    app: sonatype-nexus
    heritage: qingyuancloud
    name: nexus3
    project: sonatype.org
  name: nexus3
  # namespace: harpoon
spec:
  replicas: 1
  selector:
    name: nexus3
  template:
    metadata:
      labels:
        name: nexus3
    spec:
      containers:
      - image: tangfeixiong/sonatype-nexus:3.0.1
        imagePullPolicy: IfNotPresent
        name: nexus3
        ports:
        - containerPort: 8081
