apiVersion: v1
kind: Service
metadata:
  annotations:
    qingyuanos.io/catalog-by: '{"version": "v1alpha", "lib": "https://github.com/qingyuancloud/harpoon", "module": "https://github.com/sonatype/docker-nexus3"}'
  labels:
    app: sonatype-nexus
    heritage: qingyuancloud
    name: nexus3
    project: sonatype.org
  name: nexus3
  # namespace: harpoon
spec:
  ports:
  - name: nexus-wui
    nodePort: 32131  # Optional, or Kubernetes generate a random port if not customized
    port: 8081
    protocol: TCP
  selector:
    name: nexus3
  type: NodePort
